[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>",
          "Denys Vitali <denys@denv.it>"]
name = "poppler"
license = "GPL-2.0"
version = "0.2.5"
description = "Wrapper for the GPL-licensed Poppler PDF rendering library."
repository = "https://github.com/DMSrs/poppler-rs"

[dependencies]
cairo-rs = { version= "0.6.0", features = ["png", "pdf"]}
cairo-sys-rs = "0.8.0"
glib = "0.7.1"
glib-sys = "0.8.0"
gobject-sys = "0.8.0"
gio-sys = "0.8.0"
gtypes = "0.2.0"